// One landing page per Greenfield Ambience film: /ambience/<slug>/
//
// Used by tools/sync-ambience.mjs (never run on its own). Everything on a page comes from the
// film's own YouTube text in films.json, so a page can't claim more than the video does:
//   - the first paragraph of the description is the lede and the meta description;
//   - later paragraphs are kept unless they hold a link, a hashtag or an @handle (those are
//     YouTube housekeeping, not copy);
//   - "0:00 Label" lines become the chapter list;
//   - length, 4K and frame rate are read from the title and description, like the film cards.
// "No Loops" is the one claim a description can make that only a test can back up, so a page shows
// it ONLY when tools/film-pages.json carries the repeat-check record for that film's id.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { esc, clock as clock0, matchEol } from './youtube.mjs';
import { signupSection } from '../signup.mjs';
const clock = (s) => (s === 0 ? '0:00' : clock0(s));

export const SITE_URL = 'https://greenfieldstudio.org';
export const CHANNEL = 'https://www.youtube.com/@Greenfield.Ambience';
export const MARK = '<!-- generated by tools/sync-ambience.mjs: edit the tool, not this page -->';

const PLAY = '<svg viewBox="0 0 16 16" aria-hidden="true" focusable="false"><path d="M4.5 2.6v10.8l8.8-5.4z" fill="currentColor"/></svg>';
const BRAND = '<svg viewBox="0 0 38 22" aria-hidden="true" focusable="false"><circle cx="4.5" cy="17" r="3.6" fill="#efe8d6"/><circle cx="11" cy="9.2" r="1.1" fill="#a19b8a"/><circle cx="16.8" cy="5.4" r="1.1" fill="#a19b8a"/><circle cx="23" cy="5.2" r="1.1" fill="#a19b8a"/><circle cx="28.4" cy="9" r="1.1" fill="#a19b8a"/><circle cx="32.5" cy="17" r="4.3" fill="#050b07" stroke="#efe8d6" stroke-width="1.4"/></svg>';

/** "Coral Reef Aquarium 4K 60fps | 1 Hour Relaxing…" → "Coral Reef Aquarium"; a hand-set displayTitle wins. */
export const displayTitle = (f) => f.displayTitle || f.title.split(/\s+[|·—–]\s+/)[0].replace(/\s+4K(\s+60\s*fps)?$/i, '').trim() || f.title;

export const slugify = (s) => s.toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48).replace(/-+$/, '') || 'film';

/** Give every film a slug that never changes once it has one (so shared links keep working). */
export function ensureSlugs(db) {
  const taken = new Set(db.films.map((f) => f.slug).filter(Boolean));
  let added = 0;
  for (const f of db.films) {
    if (f.slug) continue;
    let s = slugify(displayTitle(f)), n = 2;
    while (taken.has(s)) s = `${slugify(displayTitle(f))}-${n++}`;
    f.slug = s;
    taken.add(s);
    added++;
  }
  return added;
}

/** Length in seconds: the watch page's number, else a plain "3 Hours" in the film's own title. */
export function secondsOf(f) {
  if (f.seconds) return f.seconds;
  const m = /(\d+(?:\.\d+)?)\s*(?:hours?|hrs?)\b/i.exec(f.title);
  return m ? Math.round(Number(m[1]) * 3600) : null;
}
const longLength = (s) => (s >= 5400 ? `${+(s / 3600).toFixed(1)} hours` : s >= 3300 && s < 3900 ? '1 hour' : `${Math.round(s / 60)} minutes`);
const iso = (s) => `PT${Math.floor(s / 3600)}H${Math.floor((s % 3600) / 60)}M${s % 60}S`;

function specs(f) {
  const text = `${f.title}\n${f.description || ''}`;
  const fps = /(\d{2,3})\s*(?:fps|frames per second)/i.exec(text);
  return {
    res: /3840\s*[×x]\s*2160/.test(text) ? '3840 × 2160' : /\b4K\b/i.test(text) ? '4K' : '',
    fps: fps ? `${fps[1]} fps` : '',
    noMusic: /no music/i.test(text),
  };
}

/**
 * A film whose full master has no passing repeat check (tools/film-pages.json) must not say "no loops" /
 * "never repeats" on this site, even if its YouTube text does. Known phrasings are cut cleanly; any other
 * sentence that still makes the claim is dropped.
 */
const LOOP_WORDS = /\bloops?\b|\bnever repeats?\b|\bnothing repeats\b|\bnever (?:see|hear) the same\b/i;
export function softenLoops(text) {
  let t = text
    .replace(/\bNothing in this video loops:\s*(\w)/g, (_, c) => c.toUpperCase())
    .replace(/,?\s*so (?:it|nothing) never repeats|,\s*so nothing repeats(?::[^.]*)?/gi, '')
    .replace(/\s*\bNo loops\.?/gi, '');
  if (LOOP_WORDS.test(t)) t = t.split(/(?<=[.!?])\s+/).filter((x) => !LOOP_WORDS.test(x)).join(' ');
  return t.replace(/\s+([.,])/g, '$1').trim();
}

/** Split the description into { summary, body: [{p}|{ul}], chapters: [{t, label}] }. `soften`: drop loop claims. */
export function parseDescription(f, soften = false) {
  const text0 = (f.description || '').replace(/\r/g, '').trim();
  const text = soften ? text0.split('\n').map((l) => (LOOP_WORDS.test(l) ? softenLoops(l) : l)).join('\n') : text0;
  const blocks = text.split(/\n{2,}/).map((b) => b.trim()).filter(Boolean);
  const chapters = [];
  const body = [];
  const chap = /^((?:\d{1,2}:)?\d{1,2}:\d{2})\s+(.+)$/;
  const toSec = (t) => t.split(':').reduce((a, n) => a * 60 + Number(n), 0);
  blocks.forEach((b, i) => {
    const lines = b.split('\n').map((l) => l.trim());
    if (lines.every((l) => chap.test(l))) { lines.forEach((l) => { const m = chap.exec(l); chapters.push({ s: toSec(m[1]), label: m[2] }); }); return; }
    if (i === 0) return; // the summary, used separately
    if (/https?:\/\/|(^|\s)#\w|(^|\s)@\w/.test(b)) return; // links, hashtags and handles are housekeeping
    const out = [];
    let list = null;
    for (const l of lines) {
      if (/^[-•]\s+/.test(l)) { (list ||= []).push(l.replace(/^[-•]\s+/, '')); continue; }
      if (list) { out.push({ ul: list }); list = null; }
      out.push({ p: l });
    }
    if (list) out.push({ ul: list });
    body.push(...out);
  });
  const first = blocks[0] || f.title;
  // chapters need to start at 0:00 and be at least three, or YouTube itself would not show them
  const ok = chapters.length >= 3 && chapters[0].s === 0 ? chapters : [];
  return { summary: first.replace(/\n+/g, ' '), body, chapters: ok };
}

const clip = (s, n) => (s.length <= n ? s : s.slice(0, n - 1).replace(/\s+\S*$/, '') + '…');

const head = ({ title, desc, url, ogImage, ld }) => `<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${url}">
  <meta name="theme-color" content="#0b1811">
  <meta name="color-scheme" content="dark">

  <meta property="og:type" content="video.other">
  <meta property="og:site_name" content="Greenfield Ambience · Greenfield Studio">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:url" content="${url}">
  <meta property="og:image" content="${ogImage}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">

  <link rel="icon" href="../../favicon.svg" type="image/svg+xml">
  <link rel="icon" href="../../favicon.ico" sizes="32x32">
  <link rel="apple-touch-icon" href="../../apple-touch-icon.png">
  <link rel="preload" href="../../assets/fonts/jost-latin-wght.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="../../assets/css/site.css">
  <script type="application/ld+json">
  ${JSON.stringify(ld).replace(/</g, '\\u003c')}
  </script>
  <script src="../../assets/js/site.js" defer></script>
</head>`;

const SHELL_TOP = `<header class="site-header">
    <div class="wrap">
      <a class="brand" href="../../" aria-label="Greenfield Studio, home">
        ${BRAND}
        <span class="brand-name">Greenfield Studio</span>
      </a>
      <nav class="nav" aria-label="Main"></nav>
    </div>
  </header>`;

/** One film's page, HTML. `others` = the other films, newest first. `cfg` = tools/film-pages.json entry. */
export function renderFilmPage(f, others, cfg = {}) {
  const name = displayTitle(f);
  const s = secondsOf(f);
  const sp = specs(f);
  const d = parseDescription(f, !cfg.repeatCheck);
  const url = `${SITE_URL}/ambience/${f.slug}/`;
  const watch = `https://www.youtube.com/watch?v=${f.id}`;
  const title = `${name}${s ? ` · ${longLength(s)}${sp.res ? ' in 4K' : ''}` : sp.res ? ' · 4K' : ''} · Greenfield Ambience`;
  const firstP = (d.body.find((b) => b.p) || {}).p || '';
  const desc = clip(d.summary.length < 90 && firstP ? `${d.summary} ${firstP}` : d.summary, 158);
  const thumb = `../../assets/media/ambience/films/${f.id}`;
  const spec = [s ? longLength(s) : '', sp.res ? '4K' : '', sp.fps, sp.noMusic ? 'no music' : ''].filter(Boolean).join(' · ');

  const facts = [
    s && ['length', clock(s)],
    sp.res && ['resolution', sp.res],
    sp.fps && ['frame rate', sp.fps],
    sp.noMusic && ['music', 'none'],
    cfg.repeatCheck && ['loops', 'none'],
    ['published', f.published],
    ['made by', 'Greenfield Studio'],
  ].filter(Boolean);

  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'VideoObject',
        name: f.title,
        description: d.summary,
        thumbnailUrl: `${SITE_URL}/assets/media/ambience/films/${f.id}-1280.webp`,
        uploadDate: f.published,
        ...(s ? { duration: iso(s) } : {}),
        url,
        embedUrl: `https://www.youtube-nocookie.com/embed/${f.id}`,
        publisher: { '@type': 'Organization', name: 'Greenfield Studio', url: `${SITE_URL}/` },
        ...(d.chapters.length ? {
          hasPart: d.chapters.map((c, i) => ({
            '@type': 'Clip', name: c.label, startOffset: c.s,
            ...(d.chapters[i + 1] ? { endOffset: d.chapters[i + 1].s } : s ? { endOffset: s } : {}),
            url: `${watch}&t=${c.s}s`,
          })),
        } : {}),
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Greenfield Ambience', item: `${SITE_URL}/ambience/` },
          { '@type': 'ListItem', position: 2, name, item: url },
        ],
      },
    ],
  };

  const bodyHtml = d.body.map((b) => (b.p ? `<p>${esc(b.p)}</p>` : `<ul>${b.ul.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>`)).join('\n          ');
  const chaptersHtml = d.chapters.length ? `
    <section class="section" id="chapters" aria-labelledby="chapters-title">
      <div class="wrap">
        <p class="fig"><span>fig. 02</span> <b>chapters</b></p>
        <h2 class="h2" id="chapters-title">Jump to a moment</h2>
        <ol class="chapters">
${d.chapters.map((c) => `          <li><a href="${watch}&amp;t=${c.s}s" data-start="${c.s}" rel="noopener"><span class="anno">${clock(c.s)}</span> ${esc(c.label)}</a></li>`).join('\n')}
        </ol>
      </div>
    </section>` : '';
  const more = others.slice(0, 3);
  const moreHtml = more.length ? `
    <section class="section" id="more" aria-labelledby="more-title">
      <div class="wrap">
        <p class="fig"><span>fig. ${d.chapters.length ? '03' : '02'}</span> <b>more films</b></p>
        <h2 class="h2" id="more-title">Leave another one running</h2>
        <div class="films" style="margin-top:32px">
${more.map((o) => `          <a class="film" href="../${o.slug}/">
            <span class="film-media">
              <img src="../../assets/media/ambience/films/${o.id}-640.webp" width="1280" height="720" loading="lazy" decoding="async" alt="">
              <span class="film-play" aria-hidden="true"><span class="play-disc">${PLAY}</span></span>${secondsOf(o) ? `\n              <span class="film-len">${clock(secondsOf(o))}</span>` : ''}
            </span>
            <h3>${esc(displayTitle(o))}</h3>
          </a>`).join('\n')}
        </div>
        <p style="margin-top:28px"><a class="link-arrow" href="../">All films</a></p>
      </div>
    </section>` : '';

  return `<!doctype html>
${MARK}
<html lang="en">
${head({ title, desc, url, ogImage: `${SITE_URL}/assets/media/ambience/films/${f.id}-og.jpg`, ld })}
<body>
  <a class="skip-link" href="#main">Skip to content</a>

  ${SHELL_TOP}

  <main id="main">
    <section class="section" style="padding-top:clamp(32px,6vw,72px)" aria-labelledby="film-title">
      <div class="wrap">
        <p class="fig"><span>greenfield ambience</span> <b><a href="../">all films</a></b></p>
        <h1 class="h2" id="film-title">${esc(name)}</h1>
        <p class="lede">${esc(d.summary)}</p>
        <p class="anno" style="margin:14px 0 28px">${esc(spec)}${spec ? ' · ' : ''}on YouTube</p>

        <a class="embed" href="${watch}" aria-label="Play the film: ${esc(name)}" data-embed="${f.id}" data-film-title="${esc(f.title)}" rel="noopener">
          <img src="${thumb}-1280.webp" srcset="${thumb}-640.webp 640w, ${thumb}-1280.webp 1280w" sizes="(max-width: 1180px) 100vw, 1180px" width="1280" height="720" fetchpriority="high" decoding="async" alt="Thumbnail of the film ${esc(name)}">
          <span class="film-play" aria-hidden="true"><span class="play-disc">${PLAY}</span></span>${s ? `\n          <span class="film-len">${clock(s)}</span>` : ''}
        </a>
        <div class="btn-row" style="margin-top:24px">
          <a class="btn btn--brass btn--lg" href="${CHANNEL}?sub_confirmation=1" rel="noopener">Subscribe on YouTube</a>
          <a class="btn btn--lg" href="${watch}" rel="noopener">Watch on YouTube</a>
        </div>
        <p class="muted" style="margin-top:14px;font-size:15px">The player loads from YouTube only when you press play.</p>
      </div>
    </section>

    <section class="section" aria-labelledby="about-title">
      <div class="wrap split">
        <div class="prose">
          <p class="fig"><span>fig. 01</span> <b>about this film</b></p>
          <h2 class="h2" id="about-title">What you'll see and hear</h2>
          ${bodyHtml}
          <p><a class="link-arrow" href="../">All Greenfield Ambience films</a></p>
        </div>
        <aside class="readout" aria-label="The film at a glance">
          <dl>
${facts.map(([k, v]) => `            <dt>${k}</dt><dd>${esc(v)}</dd>`).join('\n')}
          </dl>${cfg.repeatCheck ? `\n          <span class="anno">repeat check passed ${esc(cfg.repeatCheck)}</span>` : ''}
        </aside>
      </div>
    </section>${chaptersHtml}${moreHtml}${signupSection('../../') ? `
    ${signupSection('../../')}` : ''}
  </main>

  <footer class="site-footer"></footer>
</body>
</html>
`;
}

/** The part of a page that sync-chrome rewrites is masked, so a check compares only what this tool owns. */
export const mask = (html) => html.replace(/\r/g, '')
  .replace(/<nav class="nav" aria-label="Main">[\s\S]*?<\/nav>/, '<nav class="nav" aria-label="Main"></nav>')
  .replace(/<footer class="site-footer">[\s\S]*?<\/footer>/, '<footer class="site-footer"></footer>');

/** 1200 × 630 share image from the 1280 thumbnail (link-preview scrapers do not all take WebP). */
function makeOg(dir, id) {
  const out = join(dir, `${id}-og.jpg`);
  if (existsSync(out)) return true;
  const x = spawnSync('ffmpeg', ['-v', 'error', '-y', '-i', join(dir, `${id}-1280.webp`), '-vf', 'scale=1200:630:force_original_aspect_ratio=increase,crop=1200:630', '-q:v', '3', out]);
  return x.status === 0;
}

/**
 * Write (or, with check, compare) every film's page, the share images and the sitemap block.
 * Returns the list of problems when checking.
 */
export function syncFilmPages({ site, db, cfgFile, check }) {
  const dir = join(site, 'assets', 'media', 'ambience', 'films');
  const cfg = existsSync(cfgFile) ? JSON.parse(readFileSync(cfgFile, 'utf8')) : {};
  const problems = [];
  const films = db.films.filter((f) => f.slug);
  for (const f of films) {
    const others = films.filter((o) => o.id !== f.id);
    const page = join(site, 'ambience', f.slug, 'index.html');
    const html = renderFilmPage(f, others, cfg[f.id]);
    if (check) {
      if (!existsSync(page)) { problems.push(`missing ambience/${f.slug}/index.html`); continue; }
      const have = readFileSync(page, 'utf8');
      if (mask(have) !== mask(html)) problems.push(`ambience/${f.slug}/index.html differs from films.json`);
      if (!existsSync(join(dir, `${f.id}-og.jpg`))) problems.push(`missing share image ${f.id}-og.jpg`);
    } else {
      if (!makeOg(dir, f.id)) throw new Error(`no share image for ${f.id}`);
      mkdirSync(join(site, 'ambience', f.slug), { recursive: true });
      const have = existsSync(page) ? readFileSync(page, 'utf8') : '';
      // keep the menu and footer sync-chrome wrote; sync-chrome refreshes them on its own run
      let keep = html;
      const nav = have.match(/<nav class="nav" aria-label="Main">[\s\S]*?<\/nav>/), foot = have.match(/<footer class="site-footer">[\s\S]*?<\/footer>/);
      if (nav) keep = keep.replace('<nav class="nav" aria-label="Main"></nav>', () => nav[0]);
      if (foot) keep = keep.replace('<footer class="site-footer"></footer>', () => foot[0]);
      if (mask(have) !== mask(keep) || !have) writeFileSync(page, matchEol(keep, have || '\n'));
    }
  }
  // pages of films that left the site
  const slugs = new Set(films.map((f) => f.slug));
  for (const e of readdirSync(join(site, 'ambience'), { withFileTypes: true })) {
    if (!e.isDirectory() || slugs.has(e.name)) continue;
    const p = join(site, 'ambience', e.name, 'index.html');
    if (!existsSync(p) || !readFileSync(p, 'utf8').includes(MARK)) continue; // only ever remove pages this tool made
    if (check) problems.push(`ambience/${e.name}/ belongs to a film that is no longer listed`);
    else rmSync(join(site, 'ambience', e.name), { recursive: true, force: true });
  }
  // sitemap block
  const smPath = join(site, 'sitemap.xml');
  const sm = readFileSync(smPath, 'utf8');
  const block = films.map((f) => `  <url><loc>${SITE_URL}/ambience/${f.slug}/</loc><lastmod>${f.published}</lastmod></url>`).join('\n');
  const re = /(<!-- films:start -->)[\s\S]*?(<!-- films:end -->)/;
  if (!re.test(sm)) throw new Error('sitemap.xml has no films:start / films:end markers');
  const eol = sm.includes('\r\n') ? '\r\n' : '\n';
  const next = sm.replace(re, (_, a, b) => `${a}${eol}${block.replace(/\n/g, eol)}${eol}  ${b}`);
  if (check) { if (next.replace(/\r/g, '') !== sm.replace(/\r/g, '')) problems.push('sitemap.xml differs from films.json'); }
  else if (next !== sm) writeFileSync(smPath, next);
  return problems;
}
